# Generated by Django 5.0 on 2023-12-14 07:09

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the task.', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the task.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Current status of the task.', max_length=20)),
                ('deadline', models.DateTimeField(help_text='Deadline for task completion.')),
                ('vector_representation', models.JSONField(blank=True, help_text='Vector representation of the task for search functionality.', null=True)),
                ('owner', models.ForeignKey(help_text='User who owns this task.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
